
#line 2 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 13
#define YY_END_OF_BUFFER 14
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[270] =
    {   0,
        2,    2,   14,   12,    2,    1,   10,    9,    4,    4,
        4,    4,    4,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    2,
        0,    9,    0,    8,    3,    4,    0,    4,    4,    4,
        4,    4,    4,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    9,
        0,    9,    0,    0,    4,    4,    4,    4,    4,    4,
        4,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        5,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    8,    0,    8,    4,
        4,    4,    4,    4,    4,    7,    7,    7,    5,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       11,    7,    7,    7,    7,    7,    7,    7,    4,    4,
        4,    4,    4,    7,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    4,    4,    4,    4,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        4,    4,    0,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    4,    4,    0,    5,    7,    7,

        7,    7,    7,    7,    7,    7,    4,    4,    0,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        4,    0,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    4,    0,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    5,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    4,
        4,    1,    5,    4,    5,    6,    1,    7,    7,    7,
        7,    8,    7,    9,    7,    7,    7,   10,    1,    4,
        4,    4,    1,    1,   11,   12,   13,   11,   14,   11,
       11,   11,   15,   11,   16,   17,   18,   19,   20,   21,
       11,   22,   23,   24,   25,   11,   11,   26,   11,   11,
        4,    1,    4,    1,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   37,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    4,    4,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    3,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4
    } ;

static const flex_int16_t yy_base[273] =
    {   0,
        0,    0,  114, 1395,  109, 1395, 1395,   47,   50,   55,
       85,   60,   97,   67,   81,   64,   93,   77,  110,  119,
      122,  129,  132,  136,  144,  139,  147,  150,  158,  108,
      161,  186,  175,  190, 1395,  198,    0,  202,  207,  223,
      228,  232,  236,  179,  212,  249,  257,  262,  265,  268,
      271,  274,  277,  280,  283,  286,  290,  298,  301,  308,
      315,  326,  329,  341,  332,  344,  347,  350,  356,  359,
      368,  371,  374,  385,   70,  389,  395,  399,  403,  424,
      429,  420,  433,  440,  445,  450,  454,  459,  463,  466,
      476,  485,  488,  492,  495,  498,  502,  516,  519,  522,

      526,  532,  535,  538,  541,  549,  554,  565,  571,  574,
      580,  584,  588,  595,  616,  605,  601,  621,  624,  630,
      633,  637,  640,  648,  651,  654,  657,  660,  663,  671,
     1395,  674,  680,  686,  699,  702,  705,  708,  720,  724,
      730,  745,  751,  756,  716,  759,  762,  767,  772,  775,
      781,  784,  792,  798,  801,  810,  814,  818,  824,  829,
      832,  835,  839,  860,  868,  852,  843,  872,  881,  885,
      890,  894,  897,  900,  907,  910,  914,  917,  921,  932,
      935,  944,   60,  948,  951,  960,  965,  968,  975,  978,
      982,  985,  994,  997, 1000, 1028,   42, 1006, 1011, 1032,

     1035, 1038, 1044, 1050, 1056, 1060, 1077, 1081,   53, 1085,
     1088, 1091, 1094, 1098, 1102, 1106, 1109, 1116, 1119, 1127,
     1131,   36, 1136, 1141, 1144, 1147, 1158, 1161, 1164, 1175,
     1181, 1184, 1188,   27, 1192, 1196, 1204, 1209, 1222, 1226,
     1229, 1232, 1235, 1395, 1238, 1241, 1244, 1247, 1255, 1262,
     1265, 1269, 1275, 1282, 1286, 1295, 1298, 1301, 1305, 1308,
     1311, 1316, 1322, 1327, 1331, 1336, 1339, 1344, 1395, 1387,
     1390,   62
    } ;

static const flex_int16_t yy_def[273] =
    {   0,
      269,    1,  269,  269,  269,  269,  269,  269,  270,  270,
      270,  270,  270,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  269,
      269,  269,  269,  269,  269,  270,  272,  270,  270,  270,
      270,  270,  270,  269,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  269,
      269,  269,  269,  269,  272,  270,  270,  270,  270,  270,
      270,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  269,  269,  269,  270,
      270,  270,  270,  270,  270,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      269,  271,  271,  271,  271,  271,  271,  271,  270,  270,
      270,  270,  270,  271,  269,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  270,  270,  270,  270,  269,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      270,  270,  269,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  270,  270,  269,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  270,  270,  269,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      270,  269,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  270,  269,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  269,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,    0,  269,
      269,  269
    } ;

static const flex_int16_t yy_nxt[1448] =
    {   0,
        4,    5,    6,    7,    4,    4,    8,    8,    8,    4,
        9,    9,    9,    9,    9,    9,   10,    9,   11,    9,
       12,    9,    9,    9,    9,   13,    4,   14,   15,   16,
       17,   16,   18,   16,   19,   20,   16,   16,   21,   16,
       22,   23,   24,   25,   26,   27,   28,   16,   16,   29,
       16,   16,   31,   32,   32,   32,   34,   34,   34,   35,
       33,   34,   34,   34,   35,   75,   34,   34,   34,   35,
       44,   44,   44,   44,   44,   44,   37,  244,   33,  234,
      222,   37,  209,   44,   44,   44,   37,   44,   44,   44,
       38,   34,   34,   34,   35,  197,   37,   39,   42,   44,

       44,   44,   40,   34,   34,   34,   35,   46,   47,   30,
       30,   37,   41,  269,   43,   53,   44,   44,   44,  269,
       50,  269,   48,   37,   51,   44,   44,   44,   44,   44,
       44,   49,  269,  269,   52,   44,   44,   44,   44,   44,
       44,   54,   44,   44,   44,   44,   44,   44,  269,   56,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   55,
       58,  269,  269,   57,   44,   44,   44,   70,   70,   70,
       59,   62,  269,   65,   63,   64,  269,   61,  269,   71,
       60,   72,   72,   72,   66,   44,   44,   44,   67,  269,
       68,   31,   32,   32,   32,   73,   34,   34,   34,   33,

      269,  269,   69,   74,   34,   34,   34,   35,   34,   34,
       34,   35,  269,   34,   34,   34,   35,   33,   44,   44,
       44,   74,  269,  269,   37,   77,  269,  269,   37,   34,
       34,   34,   35,   37,   34,   34,   34,   35,   34,   34,
       34,   35,   34,   34,   34,   35,   78,   76,  269,   37,
      269,  269,   81,  269,   37,   44,   44,   44,   37,   80,
      269,  269,   37,   44,   44,   44,  269,   79,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,  269,   44,   44,   44,   82,

       87,   83,  269,   84,   44,   44,   44,   44,   44,   44,
       85,  269,  269,   86,   44,   44,   44,  269,   89,  269,
       88,   44,   44,   44,  269,  269,   92,  269,   91,   90,
       93,   94,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   95,  269,  269,   96,  269,   97,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   98,
      269,  100,   44,   44,   44,   70,   70,   70,  101,  269,
      269,   99,   33,  102,   72,   72,   72,   72,   72,   72,
      107,  107,  107,  269,  104,  269,  106,  103,  269,  108,
       33,  109,  109,  109,  105,   34,   34,   34,   35,  269,

      269,   34,   34,   34,   35,   34,   34,   34,   35,   34,
       34,   34,   35,  269,  269,   37,  269,  269,  112,  269,
      110,   37,  111,  269,  269,   37,   44,   44,   44,   37,
       34,   34,   34,   35,  113,   34,   34,   34,   35,   44,
       44,   44,  269,  269,  116,  115,   44,   44,   44,  269,
       37,   44,   44,   44,  269,   37,   44,   44,   44,  114,
       44,   44,   44,  269,  117,   44,   44,   44,  269,   44,
       44,   44,   44,   44,   44,  269,  119,  124,  118,  269,
      269,  120,   44,   44,   44,  269,  269,  122,  269,  121,
      123,   44,   44,   44,   44,   44,   44,  269,   44,   44,

       44,   44,   44,   44,   44,   44,   44,  125,   44,   44,
       44,  131,  269,  128,  269,  129,  269,  269,  126,  127,
      269,  119,   44,   44,   44,   44,   44,   44,   44,   44,
       44,  131,   44,   44,   44,  269,  269,  130,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
      269,  132,  269,  269,  133,   44,   44,   44,  131,  269,
      107,  107,  107,  269,  119,  269,  134,   74,  269,  137,
      136,  109,  109,  109,  269,  135,  138,  109,  109,  109,
       34,   34,   34,   35,  269,   74,   34,   34,   34,   35,
       34,   34,   34,   35,   34,   34,   34,   35,  269,  141,

       37,   34,   34,   34,   35,  269,   37,   44,   44,  145,
       37,   44,   44,   44,   37,  269,  269,  139,  269,  140,
      269,   37,   34,   34,   34,   35,  144,   44,   44,   44,
       44,   44,   44,  269,  269,  142,   44,   44,   44,   44,
       44,   44,   37,   44,   44,   44,   44,   44,   44,  269,
      269,  143,  146,  147,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,  148,  269,  269,  149,  152,   44,   44,   44,
       44,   44,   44,  150,  151,  119,   44,   44,   44,  269,
      269,  155,   44,   44,   44,  131,  269,  269,  157,  269,

      153,  269,  154,  269,  156,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,  269,  269,  158,
      269,  159,   44,  166,   44,  269,   34,   34,   34,   35,
       34,   34,   34,   35,  269,  269,   34,   34,   34,   35,
      269,  161,  160,  163,  119,  119,   37,  162,  269,  269,
       37,   34,   34,   34,   35,  113,   37,   34,   34,   34,
       35,  164,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   37,  119,   44,   44,   44,  269,   37,   44,   44,
       44,   44,   44,   44,  269,  269,  167,   44,   44,   44,
       44,   44,   44,  269,  169,  269,  165,  168,   44,   44,

       44,  269,  269,  119,   44,   44,   44,   44,   44,   44,
      269,  269,  171,  269,  269,  170,   44,   44,   44,  173,
       44,   44,   44,  269,   44,   44,   44,  269,  269,  172,
       44,   44,   44,  174,  175,   44,   44,   44,   44,   44,
       44,   34,   34,   34,   35,   34,   34,   34,   35,   44,
       44,   44,  177,  178,  176,  269,  269,  113,   44,   44,
       44,   37,  119,  183,  179,   37,   34,   34,   34,   35,
      269,  269,  180,  113,   34,   34,   34,   35,   44,   44,
       44,  269,  269,  119,  269,  269,   37,   44,   44,   44,
      269,   44,   44,   44,   37,  181,   44,   44,   44,  182,

       44,   44,   44,   44,   44,   44,   44,   44,   44,  269,
      269,  184,  185,   44,   44,   44,   44,   44,   44,  119,
       44,   44,   44,   44,   44,   44,  269,   44,   44,   44,
      187,  269,  269,  119,  189,  269,  269,  186,   44,   44,
       44,   34,   34,   34,   35,  190,  269,  188,  193,  191,
       34,   34,   34,   35,   44,   44,   44,   44,   44,   44,
      269,   37,  269,  194,  192,  269,   44,   44,   44,  269,
       37,   44,   44,   44,   44,   44,   44,  269,  269,  198,
      195,   44,   44,   44,   44,   44,   44,  196,   44,   44,
       44,   44,   44,   44,  199,  200,  119,  269,  269,  201,

       44,   44,   44,   44,   44,   44,   34,   34,   34,   35,
      269,  269,   44,   44,   44,  269,  205,   44,   44,   44,
      202,  269,  269,  203,  269,  269,   37,  206,  210,  269,
      269,  207,  119,  204,   34,   34,   34,   35,   44,   44,
       44,   44,   44,   44,   44,   44,   44,  269,  269,  212,
       44,   44,   44,  269,   37,  208,   44,   44,   44,  269,
      269,  119,   44,   44,   44,  269,   44,   44,   44,  269,
      216,  217,  211,  213,  218,  269,  219,  269,  269,  214,
      269,  215,  220,   34,   34,   34,   35,   34,   34,   34,
       35,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   37,   44,   44,   44,   37,   44,   44,
       44,  269,   44,   44,   44,   44,   44,   44,  269,  113,
      221,  119,   44,   44,   44,   44,   44,   44,  269,  269,
      223,  224,  227,   44,   44,   44,  269,   34,   34,   34,
       35,  225,   44,   44,   44,  226,  228,   44,   44,   44,
       44,   44,   44,   44,   44,   44,  230,   37,  233,  229,
      231,  232,  269,  235,   44,   44,   44,   44,   44,   44,
       44,   44,   44,  269,  269,  237,  269,  269,  238,  269,
      239,   44,   44,   44,  269,  269,  236,   44,   44,   44,
       44,   44,   44,  269,   34,   34,   34,   35,   44,   44,

       44,  269,   44,   44,   44,  269,  240,  269,  269,  241,
       44,   44,   44,  269,   37,   44,   44,   44,  247,  269,
      119,  242,  269,  248,  269,  243,  113,  246,   44,   44,
       44,  245,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,  269,  250,  269,  269,
      119,   44,   44,   44,  269,  119,  269,  249,   44,   44,
       44,   44,   44,   44,  252,   44,   44,   44,  251,  269,
      119,   44,   44,   44,  253,  269,  269,  254,   44,   44,
       44,  269,   44,   44,   44,  256,  269,  269,  255,  269,

      257,   44,   44,   44,   44,   44,   44,   44,   44,   44,
      119,   44,   44,   44,   44,   44,   44,   44,   44,   44,
      258,  260,   44,   44,   44,  269,  261,  259,   44,   44,
       44,  269,  262,   44,   44,   44,  263,   44,   44,   44,
      269,  119,   44,   44,   44,   44,   44,   44,  264,  265,
       44,   44,   44,  269,  119,  266,  269,  269,  269,  269,
      119,  269,  267,  269,  269,  269,  269,  268,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  119,  269,  269,  269,  269,  119,   36,   36,
       36,   45,  269,   45,    3,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269
    } ;

static const flex_int16_t yy_chk[1448] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    8,    8,    8,    9,    9,    9,    9,
        8,   10,   10,   10,   10,  272,   12,   12,   12,   12,
       16,   16,   16,   14,   14,   14,    9,  234,    8,  222,
      209,   10,  197,   18,   18,   18,   12,   15,   15,   15,
       10,   11,   11,   11,   11,  183,   75,   11,   12,   17,

       17,   17,   11,   13,   13,   13,   13,   14,   15,   30,
        5,   11,   11,    3,   13,   18,   19,   19,   19,    0,
       17,    0,   15,   13,   17,   20,   20,   20,   21,   21,
       21,   15,    0,    0,   17,   22,   22,   22,   23,   23,
       23,   19,   24,   24,   24,   26,   26,   26,    0,   21,
       25,   25,   25,   27,   27,   27,   28,   28,   28,   20,
       22,    0,    0,   21,   29,   29,   29,   31,   31,   31,
       22,   25,    0,   26,   25,   25,    0,   24,    0,   33,
       23,   33,   33,   33,   26,   44,   44,   44,   27,    0,
       28,   32,   32,   32,   32,   34,   34,   34,   34,   32,

        0,    0,   29,   34,   36,   36,   36,   36,   38,   38,
       38,   38,    0,   39,   39,   39,   39,   32,   45,   45,
       45,   34,    0,    0,   36,   39,    0,    0,   38,   40,
       40,   40,   40,   39,   41,   41,   41,   41,   42,   42,
       42,   42,   43,   43,   43,   43,   40,   38,    0,   40,
        0,    0,   43,    0,   41,   46,   46,   46,   42,   42,
        0,    0,   43,   47,   47,   47,    0,   41,   48,   48,
       48,   49,   49,   49,   50,   50,   50,   51,   51,   51,
       52,   52,   52,   53,   53,   53,   54,   54,   54,   55,
       55,   55,   56,   56,   56,    0,   57,   57,   57,   46,

       51,   47,    0,   48,   58,   58,   58,   59,   59,   59,
       49,    0,    0,   50,   60,   60,   60,    0,   53,    0,
       52,   61,   61,   61,    0,    0,   56,    0,   55,   54,
       57,   58,   62,   62,   62,   63,   63,   63,   65,   65,
       65,   59,    0,    0,   59,    0,   60,   64,   64,   64,
       66,   66,   66,   67,   67,   67,   68,   68,   68,   61,
        0,   63,   69,   69,   69,   70,   70,   70,   64,    0,
        0,   62,   70,   65,   71,   71,   71,   72,   72,   72,
       73,   73,   73,    0,   67,    0,   69,   66,    0,   74,
       70,   74,   74,   74,   68,   76,   76,   76,   76,    0,

        0,   77,   77,   77,   77,   78,   78,   78,   78,   79,
       79,   79,   79,    0,    0,   76,    0,    0,   78,    0,
       76,   77,   77,    0,    0,   78,   82,   82,   82,   79,
       80,   80,   80,   80,   79,   81,   81,   81,   81,   83,
       83,   83,    0,    0,   82,   81,   84,   84,   84,    0,
       80,   85,   85,   85,    0,   81,   86,   86,   86,   80,
       87,   87,   87,    0,   83,   88,   88,   88,    0,   89,
       89,   89,   90,   90,   90,    0,   85,   90,   84,    0,
        0,   86,   91,   91,   91,    0,    0,   88,    0,   87,
       89,   92,   92,   92,   93,   93,   93,    0,   94,   94,

       94,   95,   95,   95,   96,   96,   96,   91,   97,   97,
       97,   97,    0,   95,    0,   95,    0,    0,   92,   94,
        0,   93,   98,   98,   98,   99,   99,   99,  100,  100,
      100,  100,  101,  101,  101,    0,    0,   96,  102,  102,
      102,  103,  103,  103,  104,  104,  104,  105,  105,  105,
        0,   98,    0,    0,   99,  106,  106,  106,  106,    0,
      107,  107,  107,    0,  101,    0,  100,  107,    0,  104,
      103,  108,  108,  108,    0,  102,  105,  109,  109,  109,
      110,  110,  110,  110,    0,  107,  111,  111,  111,  111,
      112,  112,  112,  112,  113,  113,  113,  113,    0,  112,

      110,  114,  114,  114,  114,    0,  111,  117,  117,  117,
      112,  116,  116,  116,  113,    0,    0,  110,    0,  111,
        0,  114,  115,  115,  115,  115,  116,  118,  118,  118,
      119,  119,  119,    0,    0,  114,  120,  120,  120,  121,
      121,  121,  115,  122,  122,  122,  123,  123,  123,    0,
        0,  115,  118,  120,  124,  124,  124,  125,  125,  125,
      126,  126,  126,  127,  127,  127,  128,  128,  128,  129,
      129,  129,  121,    0,    0,  122,  126,  130,  130,  130,
      132,  132,  132,  124,  125,  123,  133,  133,  133,    0,
        0,  128,  134,  134,  134,  134,    0,    0,  130,    0,

      126,    0,  127,    0,  129,  135,  135,  135,  136,  136,
      136,  137,  137,  137,  138,  138,  138,    0,    0,  132,
        0,  133,  145,  145,  145,    0,  139,  139,  139,  139,
      140,  140,  140,  140,    0,    0,  141,  141,  141,  141,
        0,  138,  136,  141,  135,  137,  139,  139,    0,    0,
      140,  142,  142,  142,  142,  140,  141,  143,  143,  143,
      143,  142,  144,  144,  144,  146,  146,  146,  147,  147,
      147,  142,  144,  148,  148,  148,    0,  143,  149,  149,
      149,  150,  150,  150,    0,    0,  146,  151,  151,  151,
      152,  152,  152,    0,  148,    0,  143,  147,  153,  153,

      153,    0,    0,  149,  154,  154,  154,  155,  155,  155,
        0,    0,  151,    0,    0,  150,  156,  156,  156,  153,
      157,  157,  157,    0,  158,  158,  158,    0,    0,  152,
      159,  159,  159,  154,  155,  160,  160,  160,  161,  161,
      161,  162,  162,  162,  162,  163,  163,  163,  163,  167,
      167,  167,  157,  158,  156,    0,    0,  163,  166,  166,
      166,  162,  160,  166,  159,  163,  164,  164,  164,  164,
        0,    0,  161,  162,  165,  165,  165,  165,  168,  168,
      168,    0,    0,  167,    0,    0,  164,  169,  169,  169,
        0,  170,  170,  170,  165,  164,  171,  171,  171,  165,

      172,  172,  172,  173,  173,  173,  174,  174,  174,    0,
        0,  168,  170,  175,  175,  175,  176,  176,  176,  169,
      177,  177,  177,  178,  178,  178,    0,  179,  179,  179,
      173,    0,    0,  171,  175,    0,    0,  172,  180,  180,
      180,  181,  181,  181,  181,  176,    0,  174,  179,  177,
      182,  182,  182,  182,  184,  184,  184,  185,  185,  185,
        0,  181,    0,  180,  178,    0,  186,  186,  186,    0,
      182,  187,  187,  187,  188,  188,  188,    0,    0,  184,
      181,  189,  189,  189,  190,  190,  190,  182,  191,  191,
      191,  192,  192,  192,  185,  186,  187,    0,    0,  188,

      193,  193,  193,  194,  194,  194,  195,  195,  195,  195,
        0,    0,  198,  198,  198,    0,  192,  199,  199,  199,
      189,    0,    0,  190,    0,    0,  195,  194,  198,    0,
        0,  195,  193,  191,  196,  196,  196,  196,  200,  200,
      200,  201,  201,  201,  202,  202,  202,    0,    0,  201,
      203,  203,  203,    0,  196,  196,  204,  204,  204,    0,
        0,  199,  205,  205,  205,    0,  206,  206,  206,    0,
      205,  206,  200,  202,  206,    0,  206,    0,    0,  203,
        0,  204,  206,  207,  207,  207,  207,  208,  208,  208,
      208,  210,  210,  210,  211,  211,  211,  212,  212,  212,

      213,  213,  213,  207,  214,  214,  214,  208,  215,  215,
      215,    0,  216,  216,  216,  217,  217,  217,    0,  208,
      207,  211,  218,  218,  218,  219,  219,  219,    0,    0,
      210,  212,  215,  220,  220,  220,    0,  221,  221,  221,
      221,  213,  223,  223,  223,  214,  216,  224,  224,  224,
      225,  225,  225,  226,  226,  226,  218,  221,  221,  217,
      219,  220,    0,  223,  227,  227,  227,  228,  228,  228,
      229,  229,  229,    0,    0,  225,    0,    0,  226,    0,
      227,  230,  230,  230,    0,    0,  224,  231,  231,  231,
      232,  232,  232,    0,  233,  233,  233,  233,  235,  235,

      235,    0,  236,  236,  236,    0,  228,    0,    0,  229,
      237,  237,  237,    0,  233,  238,  238,  238,  237,    0,
      230,  231,    0,  238,    0,  232,  233,  236,  239,  239,
      239,  235,  240,  240,  240,  241,  241,  241,  242,  242,
      242,  243,  243,  243,  245,  245,  245,  246,  246,  246,
      247,  247,  247,  248,  248,  248,    0,  240,    0,    0,
      241,  249,  249,  249,    0,  242,    0,  239,  250,  250,
      250,  251,  251,  251,  246,  252,  252,  252,  243,    0,
      245,  253,  253,  253,  247,    0,    0,  248,  254,  254,
      254,    0,  255,  255,  255,  250,    0,    0,  249,    0,

      252,  256,  256,  256,  257,  257,  257,  258,  258,  258,
      251,  259,  259,  259,  260,  260,  260,  261,  261,  261,
      253,  255,  262,  262,  262,    0,  256,  254,  263,  263,
      263,    0,  258,  264,  264,  264,  259,  265,  265,  265,
        0,  257,  266,  266,  266,  267,  267,  267,  260,  262,
      268,  268,  268,    0,  261,  263,    0,    0,    0,    0,
      264,    0,  265,    0,    0,    0,    0,  266,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  267,    0,    0,    0,    0,  268,  270,  270,
      270,  271,    0,  271,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "Lexico.l"
#line 2 "Lexico.l"
// Inclusões de bibliotecas
#include <iostream>
#include <string>
#include <fstream>
#include <unordered_map>
using namespace std;

// Definição de constantes
enum {SOME = 256, ALL, VALUE, MIN, MAX, EXACTLY, THAT, NOT, AND, OR, CLASS, EQUIVALENTTO, INDIVIDUALS, 
SUBCLASSOF, DISJOINTCLASSES, CLASSE, PROPERTY, ID, NUM, INDIVIDUOS, NAMESPACEID, DATATYPE, BRANCA};

// Definição da tabela de símbolos (Temporária)
unordered_map<string, int> symbolTable = {
    {"some", SOME},
    {"all", ALL},
    {"value", VALUE},
    {"min", MIN},
    {"max", MAX},
    {"exactly", EXACTLY},
    {"that", THAT},
    {"not", NOT},
    {"and", AND},
    {"or", OR},
    {"Class:", CLASS},
    {"EquivalentTo:", EQUIVALENTTO},
    {"Individuals:", INDIVIDUALS},
    {"SubClassOf:", SUBCLASSOF},
    {"DisjointClasses:", DISJOINTCLASSES},
};

// Definição de mapas para armazenar as ocorrências (classes, propriedades e indivíduos)
unordered_map<string, int> classes;
unordered_map<string, int> individuos;
unordered_map<string, int> propriedades;

// Definição de funções auxiliares
void inserir(int tipo, string palavra);
int buscar(string palavra);
string toLower(string str); 

// Definição de variáveis globais
char **fileList;
unsigned nFiles;
unsigned currentFile = 0;
bool openFile, erro = false;
ifstream fin;
int numClasses, numProperties, numIndividuos, numSimbolos, numReservadas, numCardinalidades, numNamespace, numTipos = 0;
int linha = 1;
#line 848 "lex.yy.cc"
#line 849 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 68 "Lexico.l"


#line 984 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 270 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1395 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 70 "Lexico.l"
{linha++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 71 "Lexico.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "Lexico.l"
{
    auto it = symbolTable.find(yytext); 
    if (it != symbolTable.end()) {
        numReservadas++;
    } else {
        cout << "Erro de sintaxe encontrado na linha " << linha << ": " << yytext << "\n";
        erro = true;
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "Lexico.l"
{
    auto it = symbolTable.find(toLower(yytext)); 
    if (it != symbolTable.end()) {
        numReservadas++;
    } else if (isupper(yytext[0])) {
        if (classes.find(yytext) == classes.end()) {
            classes[yytext] = 1;
        } else {
            classes[yytext]++;
        }

        numClasses++;
    } else {
        cout << "Erro de sintaxe encontrado na linha " << linha << ": " << yytext << "\n";
        erro = true;
    }
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 98 "Lexico.l"
{ numTipos++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 99 "Lexico.l"
{cout << "Erro de sintaxe encontrado na linha " << linha << ": " << yytext << "\n"; erro = true;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 100 "Lexico.l"
{
    auto it = symbolTable.find(toLower(yytext));
    if (it != symbolTable.end()) {
        numReservadas++;
    } else {
        if (propriedades.find(yytext) == propriedades.end()) {
            propriedades[yytext] = 1;
        } else {
            propriedades[yytext]++;
        }
        numProperties++;
    }
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 113 "Lexico.l"
{
        numIndividuos++;        
        if (individuos.find(yytext) == individuos.end()) {
            individuos[yytext] = 1;
        } else {
            individuos[yytext]++;
        }}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 120 "Lexico.l"
{numCardinalidades++;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 121 "Lexico.l"
{numSimbolos++;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 122 "Lexico.l"
{numNamespace++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 123 "Lexico.l"
{cout << "Erro de sintaxe encontrado na linha " << linha << ": " << yytext << "\n"; erro = true;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "Lexico.l"
ECHO;
	YY_BREAK
#line 1149 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 270 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 270 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 269);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 124 "Lexico.l"


// Função principal
int main(int argc, char ** argv)
{	
    fileList = argv + 1;                                                        // Lista de arquivos         
    nFiles = argc - 1;                                                          // Número de arquivos
	
	yyFlexLexer lexer;	 		                                                // Instância do analisador léxico
    lexer.switch_streams(&fin);                                                 // Alterando o fluxo de entrada
	lexer.yywrap();				                                                // Inicializando o fluxo de entrada

	if (openFile) {                                                            // Verificando se o arquivo foi aberto
        lexer.yylex();

        if (erro) { return 1; }                                                // Verificando se houve erro

        cout << "===============================================" << endl;
        cout << "     Ocorrencias dos Elementos Presentes      " << endl;
        cout << "===============================================" << endl;

        // Exibindo o resumo geral
        cout << "Resumo Geral:" << endl;
        cout << "-----------------------------------------------" << endl;
        cout << "Classes        : " << numClasses << endl;
        cout << "Propriedades   : " << numProperties << endl;
        cout << "Individuos     : " << numIndividuos << endl;
        cout << "Simbolos       : " << numSimbolos << endl;
        cout << "Reservadas     : " << numReservadas << endl;
        cout << "Cardinalidades : " << numCardinalidades << endl;
        cout << "Namespace      : " << numNamespace << endl;
        cout << "Tipos          : " << numTipos << endl;
        cout << "-----------------------------------------------" << endl;

        // Exibindo as classes
        cout << "Classes Encontradas:" << endl;
        cout << "-----------------------------------------------" << endl;
        for (auto it = classes.begin(); it != classes.end(); it++) {
            cout << it->first << ": " << it->second << endl;
        }
        cout << "-----------------------------------------------" << endl;

        // Exibindo as propriedades
        cout << "Propriedades Encontradas:" << endl;
        cout << "-----------------------------------------------" << endl;
        for (auto it = propriedades.begin(); it != propriedades.end(); it++) {
            cout << it->first << ": " << it->second << endl;
        }
        cout << "-----------------------------------------------" << endl;

        // Exibindo os indivíduos
        cout << "Individuos Encontrados:" << endl;
        cout << "-----------------------------------------------" << endl;
        for (auto it = individuos.begin(); it != individuos.end(); it++) {
            cout << it->first << ": " << it->second << endl;
        }
        cout << "===============================================" << endl;
        cout << "\nApenas classes, propriedades e individuos foram exibidos por uma questao de estetica!\n" << endl;
    }
}

// Função de finalização
int yyFlexLexer::yywrap()
{
	if (openFile)
	{    
		openFile = false;
		fin.close();
	}

	while (!openFile && (fileList[currentFile] != nullptr)) 
    {
		fin.open(fileList[currentFile++]);
		if (fin.is_open()) 
        {
			openFile = true;
		}
		else
		{
			cout << fileList[currentFile-1] << " = não foi possível abrir\n";
		}		
	}

	return (openFile ? 0 : 1);
}

void inserir(int tipo, string palavra) {
    if (symbolTable.find(palavra) == symbolTable.end()) {
        symbolTable[palavra] = tipo;
    }
}

int buscar(string palavra) {
    auto it = symbolTable.find(palavra);
    if (it != symbolTable.end()) {
        return it->second;
    }
    return 0;
}

string toLower(string str) {
    for (int i = 0; i < str.size(); i++) {
        str[i] = tolower(str[i]);
    }
    return str;
}
