#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[273] =
    {   0,
        2,    2,   15,   13,    2,    1,    3,    6,    3,    3,
        9,    9,    9,    9,    9,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    2,    0,    6,    0,    3,    8,   12,    9,    0,
        9,    9,    9,    9,    9,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,    7,    0,    7,    9,    9,    9,    9,    9,
        9,    9,    0,    0,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    5,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,    9,
        9,    9,    5,    9,    9,   10,    0,   10,   11,   11,
       11,    5,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    4,   11,   11,   11,   11,   11,   11,
       11,    9,    9,    9,    9,    9,   11,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,    9,    9,    9,    9,   10,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    9,    9,    0,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    9,    9,    0,

        5,   11,   11,   11,   11,   11,   11,   11,   11,    9,
        9,    0,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    9,    0,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,    9,    0,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    5,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    1,    6,    7,    6,    8,    1,    9,    9,    9,
        9,   10,    9,   11,    9,    9,    9,   12,    1,   13,
       14,   15,    1,    1,   16,   17,   18,   16,   19,   16,
       16,   16,   20,   16,   21,   22,   23,   24,   25,   26,
       16,   27,   28,   29,   30,   16,   16,   31,   16,   16,
       32,    1,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,    1,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    4,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1
    } ;

static const flex_int16_t yy_base[276] =
    {   0,
        0,    0,  195, 1710,  151, 1710, 1710,   54,  138,  136,
       57,   65,   69,   73,   86,  101,  105,  112,  116,  120,
      125,  132,  136,  147,  158,  163,  167,  178,  172,  182,
      188,  137,   61,  199,  213, 1710,   79, 1710,  216,    0,
      223,  232,  236,  243,  249,  263,  270,  282,  289,  293,
      301,  305,  309,  314,  318,  322,  326,  331,  343,  354,
      358,  364,  368,  376,  383,  394,  398,  407,  411,  415,
      420,  428,  432,   91,  151,  104,  435,  443,  470,  474,
      478,  488,  206,  258,  505,  514,  482,  520,  527,  531,
      535,  540,  545,  558,  567,  571,  575,  579,  583,  589,

      604,  608,  612,  616,  622,  626,  631,  643,  647,  656,
      665,  670,  683,  691,  699,  687,  277,  297,  704,  709,
      718,  725,  734,  738,  742,  749,  755,  759,  763,  767,
      771,  783,  794, 1710,  802,  812,  816,  824,  828,  832,
      837,  847,  853,  841,  857,  861,  874,  889,  892,  900,
      906,  910,  914,  920,  924,  928,  935,  941,  945,  955,
      959,  963,  974,  978,  982,  995, 1011, 1021, 1027, 1030,
     1038, 1047, 1052, 1058, 1062, 1070, 1079, 1085, 1089, 1093,
     1105, 1112, 1116, 1128, 1132,   90, 1139, 1147, 1158, 1163,
     1175, 1179, 1183, 1194, 1198, 1206, 1210, 1215, 1229,   70,

     1219, 1233, 1246, 1250, 1256, 1262, 1267, 1272, 1276, 1291,
     1298,   71, 1302, 1306, 1310, 1317, 1324, 1328, 1339, 1350,
     1358, 1364, 1372, 1381,   54, 1385, 1389, 1393, 1400, 1412,
     1416, 1424, 1434, 1438, 1442, 1446,   36, 1450, 1454, 1461,
     1489, 1473, 1493, 1501, 1505, 1509, 1710, 1513, 1518, 1524,
     1532, 1538, 1542, 1546, 1555, 1559, 1564, 1575, 1581, 1586,
     1591, 1595, 1599, 1604, 1612, 1616, 1629, 1633, 1639, 1649,
     1653, 1710, 1703, 1706,   83
    } ;

static const flex_int16_t yy_def[276] =
    {   0,
      272,    1,  272,  272,  272,  272,  272,  272,  272,  272,
      273,  273,  273,  273,  273,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  272,  272,  272,  272,  272,  272,  272,  273,  275,
      273,  273,  273,  273,  273,  273,  272,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  272,  272,  272,  275,  273,  273,  273,  273,
      273,  273,  272,  272,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  273,
      273,  273,  273,  273,  273,  272,  272,  272,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  272,  274,  274,  274,  274,  274,  274,
      274,  273,  273,  273,  273,  273,  274,  272,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  273,  273,  273,  273,  272,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  273,  273,  272,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  273,  273,  272,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  273,
      273,  272,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  273,  272,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  273,  272,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  272,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,    0,  272,  272,  272
    } ;

static const flex_int16_t yy_nxt[1772] =
    {   0,
        4,    5,    6,    7,    7,    4,    7,    4,    8,    8,
        8,    7,    9,    4,   10,   11,   11,   11,   11,   11,
       11,   12,   11,   13,   11,   14,   11,   11,   11,   11,
       15,    7,    7,    4,   16,   17,   18,   19,   18,   20,
       18,   21,   22,   18,   18,   23,   18,   24,   25,   26,
       27,   28,   29,   30,   18,   18,   31,   18,   18,    7,
        7,   33,   34,   34,   34,   37,   37,   37,   38,   73,
       73,   73,   35,   37,   37,   37,   38,   37,   37,   37,
       38,   37,   37,   37,   38,   76,   42,   37,   37,   37,
       40,   43,   35,  247,   37,   37,   37,   38,   40,   75,

       75,   75,   40,   44,  237,  225,   40,   41,   46,   47,
       47,   47,   38,   47,   47,   47,   38,  212,   45,   40,
       47,   47,   47,   38,   47,   47,   47,   38,   47,   47,
       47,   38,  200,   47,   47,   47,   38,   40,   32,   50,
       47,   47,   47,   38,   47,   47,   47,   38,   49,   36,
       53,   36,   32,   51,   54,   47,   47,   47,   38,   75,
       75,   75,   52,   57,   55,   56,   47,   47,   47,   38,
       59,   47,   47,   47,   38,   47,   47,   47,   38,   58,
       47,   47,   47,   38,   60,   61,   47,   47,   47,   38,
       47,   47,   47,   38,  272,   62,   47,   47,   47,   38,

      272,   65,  272,  272,   66,   67,   33,   34,   34,   34,
      272,   64,  272,   63,  116,  116,  116,   35,   74,   68,
       70,   75,   75,   75,   37,   37,   37,   38,  272,   71,
       69,   37,   37,   37,   38,  272,  272,   35,  272,   72,
       37,   37,   37,   38,   37,   37,   37,   38,  272,   40,
      272,   37,   37,   37,   38,   78,   40,   37,   37,   37,
       38,  272,  272,  117,   79,   40,  118,  118,  118,   40,
      272,   37,   37,   37,   38,   77,   40,   83,   47,   47,
       47,  272,   40,   81,   82,  118,  118,  118,   84,   80,
       47,   47,   47,   38,  272,  272,   40,   47,   47,   47,

       38,   47,   47,   47,   38,  118,  118,  118,   84,   47,
       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,
       38,  272,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,  272,   47,
       47,   47,   38,  272,   86,  272,   85,  272,  272,   87,
       90,   47,   47,   47,   38,  272,  272,   88,  272,  272,
      272,   89,   47,   47,   47,   38,   47,   47,   47,   38,
       92,   91,   47,   47,   47,   38,   47,   47,   47,   38,
      272,  272,   93,   94,   47,   47,   47,   38,  272,  272,
       95,   47,   47,   47,   38,  272,  272,  272,   97,  272,

      272,   96,   47,   47,   47,   38,   47,   47,   47,   38,
      272,   98,  272,  100,   99,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,  101,   47,   47,
       47,   38,  104,  103,  272,  102,   47,   47,   47,   38,
       73,   73,   73,   37,   37,   37,   38,  272,  272,  272,
       35,   37,   37,   37,   38,  105,  272,  272,  272,  107,
      272,  106,  272,  272,  272,  109,  272,  272,   40,  272,
       35,  108,  272,  110,  272,  272,   40,  111,   37,   37,
       37,   38,   37,   37,   37,   38,   37,   37,   37,   38,
       47,   47,   47,   38,  112,  272,   37,   37,   37,   38,

      272,  272,  272,   40,  272,  272,  272,   40,  272,  115,
      272,   40,  113,   47,   47,   47,   38,  272,  272,  272,
      114,   40,   47,   47,   47,   38,  272,  121,   47,   47,
       47,   38,  272,  272,  119,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,  272,   47,   47,
       47,   38,  120,   47,   47,   47,   38,  272,  122,  272,
      272,  127,  272,  272,  272,  123,   47,   47,   47,   38,
      125,  272,  272,  124,  126,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,
       38,   47,   47,   47,   38,  272,  128,   47,   47,   47,

      134,  272,  131,  272,  132,  272,  272,  129,  272,  130,
      272,  122,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,  134,   47,   47,   47,   38,  272,  133,
       47,   47,   47,   38,   47,   47,   47,   38,  272,   47,
       47,   47,   38,  272,  272,  272,  135,  272,  272,  272,
      136,   47,   47,   47,   38,   47,   47,   47,  134,  272,
      272,  122,  272,  137,   37,   37,   37,   38,  139,  140,
      272,  272,  138,   37,   37,   37,   38,  272,   37,   37,
       37,   38,  272,  272,  272,  141,  272,  272,  272,   40,
      144,   37,   37,   37,   38,  116,  116,  116,   40,   37,

       37,   37,   38,   40,  272,   84,  142,   37,   37,   37,
       38,  143,   47,   47,   47,   38,   40,   47,   47,  148,
       38,  272,  272,  272,   40,   84,   47,   47,   47,   38,
      147,  272,   40,   47,   47,   47,   38,  272,  145,  272,
      272,  146,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,  272,  272,  149,   47,   47,   47,
       38,  272,  150,   47,   47,   47,   38,   47,   47,   47,
       38,   47,   47,   47,   38,   47,   47,   47,   38,   47,
       47,   47,   38,  272,  151,  272,  272,  152,  272,  272,
      155,   47,   47,   47,   38,  272,  272,  153,  272,  154,

      272,  122,   47,   47,   47,   38,  272,  272,  272,  158,
       47,   47,   47,   38,  272,  272,  156,  272,  272,  157,
       47,   47,   47,   38,   47,   47,   47,  134,  160,  272,
      272,  159,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,  272,   47,   47,   47,   38,   37,
       37,   37,   38,  272,  161,   37,   37,   37,   38,  166,
      162,   37,   37,   37,   38,   37,   37,   37,   38,   37,
       37,   37,   38,  272,   40,  163,  122,  164,  167,  122,
       40,  165,   47,   47,   47,   38,   40,  272,  272,  272,
       40,  113,  272,  272,   40,  122,   83,   47,  169,   47,

       47,   47,   47,   38,  272,  272,  272,   84,   47,   47,
       47,   38,  272,  168,   47,   47,   47,   38,   47,   47,
       47,   38,   47,   47,   47,   38,  170,   84,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
      172,  272,  171,   47,   47,   47,   38,  272,  122,   47,
       47,   47,   38,   47,   47,   47,   38,  272,  174,  272,
      272,  173,  176,   47,   47,   47,   38,   47,   47,   47,
       38,   47,   47,   47,   38,  272,  175,  177,  272,  272,
      272,  178,   47,   47,   47,   38,   47,   47,   47,   38,
       37,   37,   37,   38,  272,  272,  179,  272,  272,  272,

      180,  181,  272,   37,   37,   37,   38,  272,  272,  272,
      182,  272,  272,  272,  122,   40,  272,  272,  113,   37,
       37,   37,   38,  272,  272,  183,  272,  113,   40,   37,
       37,   37,   38,  272,   83,   47,   47,   47,   47,   47,
       47,   38,  272,  186,   40,   84,   47,   47,   47,   38,
      272,  272,  272,  184,   40,   47,   47,   47,   38,  185,
       47,   47,   47,   38,  272,   84,   47,   47,   47,   38,
       47,   47,   47,   38,  272,  272,  272,  122,   47,   47,
       47,   38,  272,  272,  187,  272,  188,   47,   47,   47,
       38,  272,  122,   47,   47,   47,   38,   47,   47,   47,

       38,   47,   47,   47,   38,  272,  272,  272,  122,  272,
      190,  272,  189,   47,   47,   47,   38,  272,  272,  192,
       47,   47,   47,   38,   47,   47,   47,   38,  272,  272,
      272,  193,  272,  191,  272,  194,   37,   37,   37,   38,
       37,   37,   37,   38,  272,  272,  196,   47,   47,   47,
       38,  272,  272,  272,  197,   47,   47,   47,   38,  195,
      272,   40,  272,  272,  272,   40,   47,   47,   47,   38,
      272,   47,   47,   47,   38,  272,  272,  201,  272,  272,
      198,  272,  199,   47,   47,   47,   38,   47,   47,   47,
       38,   47,   47,   47,   38,  272,  272,  202,  272,  272,

      203,  122,   47,   47,   47,   38,   47,   47,   47,   38,
      272,  272,  272,  204,   47,   47,   47,   38,   47,   47,
       47,   38,  272,   37,   37,   37,   38,   47,   47,   47,
       38,  205,  272,  272,  272,  206,  208,   37,   37,   37,
       38,   47,   47,   47,   38,  272,  213,  209,   40,  272,
      272,  122,  207,  210,   47,   47,   47,   38,   47,   47,
       47,   38,   40,  211,   47,   47,   47,   38,  272,  215,
       47,   47,   47,   38,  272,   47,   47,   47,   38,  272,
       47,   47,   47,   38,   47,   47,   47,   38,  272,  272,
      122,  219,  220,  214,  272,  221,  272,  222,  216,   37,

       37,   37,   38,  223,  217,  218,   37,   37,   37,   38,
       47,   47,   47,   38,   47,   47,   47,   38,   47,   47,
       47,   38,  272,  272,   40,   47,   47,   47,   38,  272,
      272,   40,   47,   47,   47,   38,   47,   47,   47,   38,
      272,  224,  272,  113,  272,  272,  122,   47,   47,   47,
       38,  272,  272,  272,  226,  272,  272,  227,   47,   47,
       47,   38,  272,  272,  272,  230,   47,   47,   47,   38,
      272,  228,   47,   47,   47,   38,  272,  272,  229,  272,
       47,   47,   47,   38,  272,  272,  231,  272,  272,   37,
       37,   37,   38,   47,   47,   47,   38,   47,   47,   47,

       38,   47,   47,   47,   38,  233,  272,  232,   47,   47,
       47,   38,  234,  235,   40,  236,  272,  272,  272,  238,
       47,   47,   47,   38,   47,   47,   47,   38,  272,  272,
      272,  240,   47,   47,   47,   38,  272,  272,  241,  242,
      272,  239,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,   37,   37,   37,   38,   47,   47,
       47,   38,   47,   47,   47,   38,  272,  272,  243,   47,
       47,   47,   38,  272,  272,  272,  244,  272,  272,   40,
      250,   47,   47,   47,   38,  245,  122,  272,  272,  272,
      246,  113,  249,  272,  272,  272,  248,   47,   47,   47,

       38,   47,   47,   47,   38,  272,  272,  272,  251,   47,
       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,
       38,   47,   47,   47,   38,  252,   47,   47,   47,   38,
      272,  253,   47,   47,   47,   38,  272,  272,  272,  122,
       47,   47,   47,   38,  272,  122,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,  255,  254,
      272,  272,  122,   47,   47,   47,   38,   47,   47,   47,
       38,  256,   47,   47,   47,   38,  272,  272,  272,  257,
      272,  272,  259,   47,   47,   47,   38,  272,  258,   47,
       47,   47,   38,  260,   47,   47,   47,   38,  122,   47,

       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,
       38,  261,   47,   47,   47,   38,  262,  263,  272,  264,
       47,   47,   47,   38,   47,   47,   47,   38,  272,  265,
      272,  272,  272,  266,  272,  272,  122,   47,   47,   47,
       38,   47,   47,   47,   38,  272,  267,   47,   47,   47,
       38,  272,  268,  272,  122,  272,  269,   47,   47,   47,
       38,   47,   47,   47,   38,  272,  272,  272,  272,  122,
      272,  270,  272,  272,  272,  272,  272,  271,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  122,

      272,  272,  272,  122,   39,   39,   39,   48,   48,    3,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272
    } ;

static const flex_int16_t yy_chk[1772] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    8,    8,    8,   11,   11,   11,   11,   33,
       33,   33,    8,   12,   12,   12,   12,   13,   13,   13,
       13,   14,   14,   14,   14,  275,   13,   37,   37,   37,
       11,   13,    8,  237,   15,   15,   15,   15,   12,   74,

       74,   74,   13,   13,  225,  212,   14,   12,   15,   16,
       16,   16,   16,   17,   17,   17,   17,  200,   14,   15,
       18,   18,   18,   18,   19,   19,   19,   19,   20,   20,
       20,   20,  186,   21,   21,   21,   21,   76,   32,   17,
       22,   22,   22,   22,   23,   23,   23,   23,   16,   10,
       19,    9,    5,   17,   19,   24,   24,   24,   24,   75,
       75,   75,   17,   21,   19,   20,   25,   25,   25,   25,
       23,   26,   26,   26,   26,   27,   27,   27,   27,   22,
       29,   29,   29,   29,   23,   24,   28,   28,   28,   28,
       30,   30,   30,   30,    3,   24,   31,   31,   31,   31,

        0,   27,    0,    0,   27,   27,   34,   34,   34,   34,
        0,   26,    0,   25,   83,   83,   83,   34,   35,   28,
       29,   35,   35,   35,   39,   39,   39,   39,    0,   30,
       28,   41,   41,   41,   41,    0,    0,   34,    0,   31,
       42,   42,   42,   42,   43,   43,   43,   43,    0,   39,
        0,   44,   44,   44,   44,   42,   41,   45,   45,   45,
       45,    0,    0,   84,   43,   42,   84,   84,   84,   43,
        0,   46,   46,   46,   46,   41,   44,   47,   47,   47,
       47,    0,   45,   45,   46,  117,  117,  117,   47,   44,
       48,   48,   48,   48,    0,    0,   46,   49,   49,   49,

       49,   50,   50,   50,   50,  118,  118,  118,   47,   51,
       51,   51,   51,   52,   52,   52,   52,   53,   53,   53,
       53,    0,   54,   54,   54,   54,   55,   55,   55,   55,
       56,   56,   56,   56,   57,   57,   57,   57,    0,   58,
       58,   58,   58,    0,   50,    0,   49,    0,    0,   51,
       54,   59,   59,   59,   59,    0,    0,   52,    0,    0,
        0,   53,   60,   60,   60,   60,   61,   61,   61,   61,
       56,   55,   62,   62,   62,   62,   63,   63,   63,   63,
        0,    0,   57,   58,   64,   64,   64,   64,    0,    0,
       59,   65,   65,   65,   65,    0,    0,    0,   61,    0,

        0,   60,   66,   66,   66,   66,   67,   67,   67,   67,
        0,   62,    0,   63,   62,   68,   68,   68,   68,   69,
       69,   69,   69,   70,   70,   70,   70,   64,   71,   71,
       71,   71,   67,   66,    0,   65,   72,   72,   72,   72,
       73,   73,   73,   77,   77,   77,   77,    0,    0,    0,
       73,   78,   78,   78,   78,   68,    0,    0,    0,   70,
        0,   69,    0,    0,    0,   72,    0,    0,   77,    0,
       73,   71,    0,   77,    0,    0,   78,   78,   79,   79,
       79,   79,   80,   80,   80,   80,   81,   81,   81,   81,
       87,   87,   87,   87,   79,    0,   82,   82,   82,   82,

        0,    0,    0,   79,    0,    0,    0,   80,    0,   82,
        0,   81,   80,   85,   85,   85,   85,    0,    0,    0,
       81,   82,   86,   86,   86,   86,    0,   87,   88,   88,
       88,   88,    0,    0,   85,   89,   89,   89,   89,   90,
       90,   90,   90,   91,   91,   91,   91,    0,   92,   92,
       92,   92,   86,   93,   93,   93,   93,    0,   88,    0,
        0,   93,    0,    0,    0,   89,   94,   94,   94,   94,
       91,    0,    0,   90,   92,   95,   95,   95,   95,   96,
       96,   96,   96,   97,   97,   97,   97,   98,   98,   98,
       98,   99,   99,   99,   99,    0,   94,  100,  100,  100,

      100,    0,   98,    0,   98,    0,    0,   95,    0,   97,
        0,   96,  101,  101,  101,  101,  102,  102,  102,  102,
      103,  103,  103,  103,  104,  104,  104,  104,    0,   99,
      105,  105,  105,  105,  106,  106,  106,  106,    0,  107,
      107,  107,  107,    0,    0,    0,  101,    0,    0,    0,
      102,  108,  108,  108,  108,  109,  109,  109,  109,    0,
        0,  104,    0,  103,  110,  110,  110,  110,  106,  107,
        0,    0,  105,  111,  111,  111,  111,    0,  112,  112,
      112,  112,    0,    0,    0,  108,    0,    0,    0,  110,
      112,  113,  113,  113,  113,  116,  116,  116,  111,  114,

      114,  114,  114,  112,    0,  116,  110,  115,  115,  115,
      115,  111,  119,  119,  119,  119,  113,  120,  120,  120,
      120,    0,    0,    0,  114,  116,  121,  121,  121,  121,
      119,    0,  115,  122,  122,  122,  122,    0,  114,    0,
        0,  115,  123,  123,  123,  123,  124,  124,  124,  124,
      125,  125,  125,  125,    0,    0,  121,  126,  126,  126,
      126,    0,  123,  127,  127,  127,  127,  128,  128,  128,
      128,  129,  129,  129,  129,  130,  130,  130,  130,  131,
      131,  131,  131,    0,  124,    0,    0,  125,    0,    0,
      129,  132,  132,  132,  132,    0,    0,  127,    0,  128,

        0,  126,  133,  133,  133,  133,    0,    0,    0,  131,
      135,  135,  135,  135,    0,    0,  129,    0,    0,  130,
      136,  136,  136,  136,  137,  137,  137,  137,  133,    0,
        0,  132,  138,  138,  138,  138,  139,  139,  139,  139,
      140,  140,  140,  140,    0,  141,  141,  141,  141,  144,
      144,  144,  144,    0,  135,  142,  142,  142,  142,  144,
      136,  143,  143,  143,  143,  145,  145,  145,  145,  146,
      146,  146,  146,    0,  144,  139,  138,  141,  145,  140,
      142,  142,  147,  147,  147,  147,  143,    0,    0,    0,
      145,  143,    0,    0,  146,  147,  148,  148,  148,  148,

      149,  149,  149,  149,    0,    0,    0,  148,  150,  150,
      150,  150,    0,  146,  151,  151,  151,  151,  152,  152,
      152,  152,  153,  153,  153,  153,  149,  148,  154,  154,
      154,  154,  155,  155,  155,  155,  156,  156,  156,  156,
      151,    0,  150,  157,  157,  157,  157,    0,  152,  158,
      158,  158,  158,  159,  159,  159,  159,    0,  154,    0,
        0,  153,  156,  160,  160,  160,  160,  161,  161,  161,
      161,  162,  162,  162,  162,    0,  155,  157,    0,    0,
        0,  158,  163,  163,  163,  163,  164,  164,  164,  164,
      165,  165,  165,  165,    0,    0,  159,    0,    0,    0,

      160,  161,    0,  166,  166,  166,  166,    0,    0,    0,
      162,    0,    0,    0,  163,  165,    0,    0,  166,  167,
      167,  167,  167,    0,    0,  164,    0,  165,  166,  168,
      168,  168,  168,    0,  169,  169,  169,  169,  170,  170,
      170,  170,    0,  169,  167,  169,  171,  171,  171,  171,
        0,    0,    0,  167,  168,  172,  172,  172,  172,  168,
      173,  173,  173,  173,    0,  169,  174,  174,  174,  174,
      175,  175,  175,  175,    0,    0,    0,  170,  176,  176,
      176,  176,    0,    0,  171,    0,  173,  177,  177,  177,
      177,    0,  172,  178,  178,  178,  178,  179,  179,  179,

      179,  180,  180,  180,  180,    0,    0,    0,  174,    0,
      176,    0,  175,  181,  181,  181,  181,    0,    0,  178,
      182,  182,  182,  182,  183,  183,  183,  183,    0,    0,
        0,  179,    0,  177,    0,  180,  184,  184,  184,  184,
      185,  185,  185,  185,    0,    0,  182,  187,  187,  187,
      187,    0,    0,    0,  183,  188,  188,  188,  188,  181,
        0,  184,    0,    0,    0,  185,  189,  189,  189,  189,
        0,  190,  190,  190,  190,    0,    0,  187,    0,    0,
      184,    0,  185,  191,  191,  191,  191,  192,  192,  192,
      192,  193,  193,  193,  193,    0,    0,  188,    0,    0,

      189,  190,  194,  194,  194,  194,  195,  195,  195,  195,
        0,    0,    0,  191,  196,  196,  196,  196,  197,  197,
      197,  197,    0,  198,  198,  198,  198,  201,  201,  201,
      201,  192,    0,    0,    0,  193,  195,  199,  199,  199,
      199,  202,  202,  202,  202,    0,  201,  197,  198,    0,
        0,  196,  194,  198,  203,  203,  203,  203,  204,  204,
      204,  204,  199,  199,  205,  205,  205,  205,    0,  204,
      206,  206,  206,  206,    0,  207,  207,  207,  207,    0,
      208,  208,  208,  208,  209,  209,  209,  209,    0,    0,
      202,  208,  209,  203,    0,  209,    0,  209,  205,  210,

      210,  210,  210,  209,  206,  207,  211,  211,  211,  211,
      213,  213,  213,  213,  214,  214,  214,  214,  215,  215,
      215,  215,    0,    0,  210,  216,  216,  216,  216,    0,
        0,  211,  217,  217,  217,  217,  218,  218,  218,  218,
        0,  210,    0,  211,    0,    0,  214,  219,  219,  219,
      219,    0,    0,    0,  213,    0,    0,  215,  220,  220,
      220,  220,    0,    0,    0,  218,  221,  221,  221,  221,
        0,  216,  222,  222,  222,  222,    0,    0,  217,    0,
      223,  223,  223,  223,    0,    0,  219,    0,    0,  224,
      224,  224,  224,  226,  226,  226,  226,  227,  227,  227,

      227,  228,  228,  228,  228,  221,    0,  220,  229,  229,
      229,  229,  222,  223,  224,  224,    0,    0,    0,  226,
      230,  230,  230,  230,  231,  231,  231,  231,    0,    0,
        0,  228,  232,  232,  232,  232,    0,    0,  229,  230,
        0,  227,  233,  233,  233,  233,  234,  234,  234,  234,
      235,  235,  235,  235,  236,  236,  236,  236,  238,  238,
      238,  238,  239,  239,  239,  239,    0,    0,  231,  240,
      240,  240,  240,    0,    0,    0,  232,    0,    0,  236,
      240,  242,  242,  242,  242,  234,  233,    0,    0,    0,
      235,  236,  239,    0,    0,    0,  238,  241,  241,  241,

      241,  243,  243,  243,  243,    0,    0,    0,  241,  244,
      244,  244,  244,  245,  245,  245,  245,  246,  246,  246,
      246,  248,  248,  248,  248,  242,  249,  249,  249,  249,
        0,  243,  250,  250,  250,  250,    0,    0,    0,  244,
      251,  251,  251,  251,    0,  245,  252,  252,  252,  252,
      253,  253,  253,  253,  254,  254,  254,  254,  249,  246,
        0,    0,  248,  255,  255,  255,  255,  256,  256,  256,
      256,  250,  257,  257,  257,  257,    0,    0,    0,  251,
        0,    0,  253,  258,  258,  258,  258,    0,  252,  259,
      259,  259,  259,  255,  260,  260,  260,  260,  254,  261,

      261,  261,  261,  262,  262,  262,  262,  263,  263,  263,
      263,  256,  264,  264,  264,  264,  257,  258,    0,  259,
      265,  265,  265,  265,  266,  266,  266,  266,    0,  261,
        0,    0,    0,  262,    0,    0,  260,  267,  267,  267,
      267,  268,  268,  268,  268,    0,  263,  269,  269,  269,
      269,    0,  265,    0,  264,    0,  266,  270,  270,  270,
      270,  271,  271,  271,  271,    0,    0,    0,    0,  267,
        0,  268,    0,    0,    0,    0,    0,  269,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  270,

        0,    0,    0,  271,  273,  273,  273,  274,  274,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[15] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexico.l"
#line 2 "Lexico.l"
// Inclusões de bibliotecas
#include <iostream>
#include <string>
#include <unordered_map>
#include <algorithm>
#include <vector>
#include <cstring>
#include "symtable.h"
using std::cout;
using std::string;
using std::unordered_map;
using std::transform;
using std::vector;

#include "Sintatico.tab.h" 

// Definição da tabela de palavras reservadas
unordered_map<string, int> reservadas = {
    {"only", ONLY},
    {"some", SOME},
    {"all", ALL},
    {"value", VALUE},
    {"min", MIN},
    {"max", MAX},
    {"exactly", EXACTLY},
    {"that", THAT},
    {"not", NOT},
    {"and", AND},
    {"or", OR},
    {"class:", CLASS},
    {"equivalentto:", EQUIVALENTTO},
    {"individuals:", INDIVIDUALS},
    {"subclassof:", SUBCLASSOF},
    {"disjointclasses:", DISJOINTCLASSES},
    {"disjointwith:", DISJOINTWITH},
    {"class", ERROR},
    {"equivalentto", ERROR},
    {"individuals", ERROR},
    {"subclassof", ERROR},
    {"disjointclasses", ERROR},
    {"disjointwith", ERROR}
};

// Definição de funções auxiliares
string toLower(string str);

// Definição de variáveis globais
bool erro = false;
int line_number = 1;
extern SymTable * currentTable;
extern SymTable * globalTable;
#line 1002 "lex.yy.c"
#define YY_NO_INPUT 1
#line 1004 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 77 "Lexico.l"

#line 1221 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1710 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 78 "Lexico.l"
{ line_number++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 79 "Lexico.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "Lexico.l"
{
    switch (yytext[0]) {
        case '<':
            if (yytext[1] == '=') {
                return TAG_MENORIGUAL;  // '<='
            } else {
                return TAG_MENOR;       // '<'
            }
        case '>':
            if (yytext[1] == '=') {
                return TAG_MAIORIGUAL;  // '>='
            } else {
                return TAG_MAIOR;       // '>'
            }
        case '[':
            return TAG_ABRECOLCHETE;  // '['
        case ']':
            return TAG_FECHACOLCHETE;  // ']'
        case '{':
            return TAG_ABRECHAVE;     // '{'
        case '}':
            return TAG_FECHACHAVE;    // '}'
        case '(':
            return TAG_ABREPARANTESIS;  // '('
        case ')':
            return TAG_FECHAPARANTESIS;  // ')'
        case ',':
            return TAG_VIRGULA;        // ','
        case ':':
            return TAG_DOISPONTOS;     // ':'
        default:
            return 0;  // caso de erro
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 114 "Lexico.l"
{ yylval.str = strdup(yytext); return TAG_NAMESPACE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 115 "Lexico.l"
{ yylval.str = strdup(yytext); return TAG_DATATYPE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 116 "Lexico.l"
{ yylval.numI = atoi(yytext); return TAG_NUMI; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 117 "Lexico.l"
{ yylval.numD = atof(yytext); return TAG_NUMD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 118 "Lexico.l"
{ 
    std::string className = yytext;
    Symblo newSymblo = {currentTable->getClassName()};  
    currentTable->Insert(className, newSymblo);  
    yylval.str = strdup(yytext); 
    return TAG_INDIVIDUOS; 
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 125 "Lexico.l"
{
    auto it = reservadas.find(toLower(yytext)); 

    if (it != reservadas.end()) {
        if (it->second == ERROR) {
            cout << "Erro lexico encontrado [" << yytext << "] na linha " << line_number << ". Após a palavra reservada " << yytext << " deve vir ':'.\n";
            exit(1);
        }
        return it->second;
    } else {
        if (currentTable->getClassName().empty())
        {
            std::string className = yytext;
            currentTable->setClassName(className);
        }
        yylval.str = strdup(yytext);
        return TAG_CLASS;
    }
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 144 "Lexico.l"
{ cout << "Erro lexico encontrado na linha " << line_number << ": " << yytext << "\n"; exit(1); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 145 "Lexico.l"
{
    auto it = reservadas.find(toLower(yytext));
    if (it != reservadas.end()) {
        if (it->second == ERROR) {
            cout << "Erro lexico encontrado [" << yytext << "] na linha " << line_number << ". Após a palavra reservada " << yytext << " deve vir ':'.\n";
            exit(1);
        }
        return it->second;
    } else {
        yylval.str = strdup(yytext);
        return TAG_PROPERTY;
    }
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "Lexico.l"
{
    auto it = reservadas.find(toLower(yytext)); 
    if (it != reservadas.end()) {
        if (it->second == CLASS) {
            // Nova tabela de símbolos
            SymTable * newScope = new SymTable(globalTable);
            currentTable = newScope;
        }
        return it->second; 
    } else {
        cout << "Erro lexico encontrado na linha " << line_number << ": " << yytext << "\n";
        exit(1);
    }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 172 "Lexico.l"
{ cout << "\nErro lexico encontrado na linha " << line_number << ": " << yytext << "\n"; exit(1); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 173 "Lexico.l"
ECHO;
	YY_BREAK
#line 1441 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 272);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 173 "Lexico.l"


string toLower(string str) {
    transform(str.begin(), str.end(), str.begin(), [](unsigned char c) { return tolower(c); });
    return str;
}
