#line 1 "lex.yy.c"

#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 13
#define YY_END_OF_BUFFER 14
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[278] =
    {   0,
        2,    2,   14,   12,    2,    1,    3,    6,    3,    3,
        8,    8,    8,    8,    8,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    2,    0,    6,    0,    3,    7,   11,    8,    0,
        8,    8,    8,    8,    8,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    6,    0,    6,    0,    0,    8,    8,    8,
        8,    8,    8,    8,    0,    0,   10,   10,   10,   10,
       10,   10,   10,   10,   10,    5,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    7,    0,    7,    8,    8,    8,    5,    8,    8,
        9,    0,    9,   10,   10,   10,    5,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    4,   10,
       10,   10,   10,   10,   10,   10,    8,    8,    8,    8,
        8,   10,    9,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,    8,
        8,    8,    8,    9,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    8,    8,
        0,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,    8,    8,    0,    5,   10,   10,   10,   10,
       10,   10,   10,   10,    8,    8,    0,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    8,    0,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        8,    0,   10,   10,   10,   10,   10,   10,   10,   10,
       10,    5,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    1,    6,    7,    6,    8,    1,    9,    9,    9,
        9,   10,    9,   11,    9,    9,    9,   12,    1,   13,
       14,   15,    1,    1,   16,   17,   18,   16,   19,   16,
       16,   16,   20,   16,   21,   22,   23,   24,   25,   26,
       16,   27,   28,   29,   30,   16,   16,   31,   16,   16,
       32,    1,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,    1,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    4,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1
    } ;

static const flex_int16_t yy_base[281] =
    {   0,
        0,    0,  195, 1755,  151, 1755, 1755,   54,  138,  136,
       57,   65,   69,   73,   86,  101,  105,  112,  116,  120,
      125,  132,  136,  147,  158,  163,  167,  178,  172,  182,
      188,  137,   61,  199,  213, 1755,  217, 1755,  223,    0,
      232,  236,  240,  252,  266,  270,  279,  284,  296,  300,
      304,  310,  314,  318,  322,  326,  330,  335,  347,  359,
      339,  372,  380,  387,  391,  400,  406,  418,  422,  426,
      436,  440,  355,   79,   91,  151,  262,  104,  445,  451,
      465,  471,  482,  486,  206,  459,  491,  502,  517,  521,
      525,  533,  537,  542,  557,  546,  569,  577,  581,  585,

      589,  593,  603,  610,  614,  618,  622,  628,  633,  638,
      645,  649,  244,  351,  665,  673,  680,  684,  693,  699,
      712,  368,  395,  725,  734,  738,  744,  749,  753,  757,
      761,  770,  774,  778,  782,  786,  798,  807, 1755,  811,
      817,  827,  834,  840,  844,  848,  859,  863,  867,  873,
      894,  899,  904,  907,  915,  920,  924,  928,  939,  950,
      955,  959,  963,  970,  974,  982,  986,  996, 1000, 1004,
     1017, 1021, 1033, 1049, 1064, 1068, 1072, 1081, 1085, 1089,
     1093, 1097, 1110, 1114, 1118, 1132, 1137, 1144, 1154, 1158,
       90, 1164, 1168, 1184, 1189, 1201, 1205, 1211, 1220, 1224,

     1232, 1236, 1241, 1250,   70, 1245, 1256, 1260, 1277, 1281,
     1289, 1294, 1300, 1306, 1326, 1330,   71, 1334, 1338, 1342,
     1346, 1356, 1360, 1371, 1382, 1393, 1397, 1403, 1413,   54,
     1417, 1421, 1425, 1444, 1448, 1456, 1460, 1468, 1475, 1479,
     1483,   36, 1487, 1491, 1495, 1515, 1527, 1531, 1535, 1540,
     1544, 1755, 1548, 1552, 1556, 1566, 1573, 1577, 1590, 1596,
     1600, 1610, 1616, 1621, 1627, 1635, 1640, 1645, 1655, 1659,
     1671, 1675, 1679, 1685, 1692, 1698, 1755, 1748, 1751,   83
    } ;

static const flex_int16_t yy_def[281] =
    {   0,
      277,    1,  277,  277,  277,  277,  277,  277,  277,  277,
      278,  278,  278,  278,  278,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  277,  277,  277,  277,  277,  277,  277,  278,  280,
      278,  278,  278,  278,  278,  278,  277,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  277,  277,  277,  277,  277,  280,  278,  278,
      278,  278,  278,  278,  277,  277,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  277,  277,  277,  278,  278,  278,  278,  278,  278,
      277,  277,  277,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  277,  279,
      279,  279,  279,  279,  279,  279,  278,  278,  278,  278,
      278,  279,  277,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  278,
      278,  278,  278,  277,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  278,  278,
      277,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  278,  278,  277,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  278,  278,  277,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  278,  277,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      278,  277,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  277,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,    0,  277,  277,  277
    } ;

static const flex_int16_t yy_nxt[1817] =
    {   0,
        4,    5,    6,    7,    7,    4,    7,    4,    8,    8,
        8,    7,    9,    4,   10,   11,   11,   11,   11,   11,
       11,   12,   11,   13,   11,   14,   11,   11,   11,   11,
       15,    7,    7,    4,   16,   17,   18,   19,   18,   20,
       18,   21,   22,   18,   18,   23,   18,   24,   25,   26,
       27,   28,   29,   30,   18,   18,   31,   18,   18,    7,
        7,   33,   34,   34,   34,   37,   37,   37,   38,   73,
       73,   73,   35,   37,   37,   37,   38,   37,   37,   37,
       38,   37,   37,   37,   38,   78,   42,   75,   75,   75,
       40,   43,   35,  252,   37,   37,   37,   38,   40,   75,

       75,   75,   40,   44,  242,  230,   40,   41,   46,   47,
       47,   47,   38,   47,   47,   47,   38,  217,   45,   40,
       47,   47,   47,   38,   47,   47,   47,   38,   47,   47,
       47,   38,  205,   47,   47,   47,   38,   40,   32,   50,
       47,   47,   47,   38,   47,   47,   47,   38,   49,   36,
       53,   36,   32,   51,   54,   47,   47,   47,   38,  112,
      112,  112,   52,   57,   55,   56,   47,   47,   47,   38,
       59,   47,   47,   47,   38,   47,   47,   47,   38,   58,
       47,   47,   47,   38,   60,   61,   47,   47,   47,   38,
       47,   47,   47,   38,  277,   62,   47,   47,   47,   38,

      277,   65,  277,  277,   66,   67,   33,   34,   34,   34,
      277,   64,  277,   63,  121,  121,  121,   35,   74,   68,
       70,   75,   75,   75,   76,   37,   37,   37,  277,   71,
       69,   37,   37,   37,   38,   77,  277,   35,  277,   72,
       37,   37,   37,   38,   37,   37,   37,   38,   37,   37,
       37,   38,  114,  114,  114,   77,   40,  277,  277,   80,
       37,   37,   37,   38,  277,   40,  277,  113,   81,   40,
      114,  114,  114,   40,   37,   37,   37,   38,   37,   37,
       37,   38,  277,  277,   79,   40,   85,   47,   47,   47,
      277,   84,   47,   47,   47,   38,  277,   86,   82,   40,

       83,  277,  277,   40,   47,   47,   47,   38,   47,   47,
       47,   38,   47,   47,   47,   38,  277,   86,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,   47,   47,
       47,   38,  277,   47,   47,   47,   38,   47,   47,   47,
       38,   88,   89,   87,   92,   47,   47,   47,   38,  114,
      114,  114,   90,   73,   73,   73,   91,   47,   47,   47,
       38,  277,  277,   35,   94,   93,  123,  123,  123,   99,
       47,   47,   47,   38,  277,  277,   95,   96,   47,   47,
       47,   38,  277,   35,   97,   47,   47,   47,   38,   47,

       47,   47,   38,  123,  123,  123,   98,  277,   47,   47,
       47,   38,  277,  277,   47,   47,   47,   38,  277,  100,
      277,  277,  101,  277,  277,  102,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,  103,  105,
      106,  277,  277,  104,   47,   47,   47,   38,   47,   47,
       47,   38,  277,   37,   37,   37,   38,  277,  277,   37,
       37,   37,   38,  277,  122,  277,  107,  123,  123,  123,
      109,  277,  108,   37,   37,   37,   38,  111,   40,   37,
       37,   37,   38,  115,   40,  116,  277,  110,  277,  117,
       37,   37,   37,   38,   37,   37,   37,   38,   40,   47,

       47,   47,   38,  277,   40,  277,  277,  120,  277,  118,
       47,   47,   47,   38,  277,   40,  277,  277,  277,   40,
      124,  277,  277,  277,  119,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,  277,  277,  277,
      125,   47,   47,   47,   38,   47,   47,   47,   38,  277,
       47,   47,   47,   38,   47,   47,   47,   38,  277,  127,
      277,  277,  126,  128,  277,   47,   47,   47,   38,  277,
      277,  277,  130,  132,  277,  129,  131,   47,   47,   47,
       38,  277,  277,  277,  133,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,

       38,   47,   47,   47,  139,  277,  277,  277,  136,  134,
      137,   47,   47,   47,   38,  135,  277,  127,   47,   47,
       47,   38,   47,   47,   47,  139,   47,   47,   47,   38,
       47,   47,   47,   38,  277,  138,   47,   47,   47,   38,
      277,   47,   47,   47,   38,  140,   47,   47,   47,   38,
      277,  277,  141,   47,   47,   47,  139,  112,  112,  112,
      277,  277,  277,  127,  277,  142,  277,   77,  277,  277,
      144,  145,  143,   37,   37,   37,   38,  277,  277,  277,
      146,   37,   37,   37,   38,  277,  277,   77,   37,   37,
       37,   38,   37,   37,   37,   38,  277,  277,   40,  277,

      149,   37,   37,   37,   38,  277,   40,   37,   37,   37,
       38,  277,  277,   40,  277,  147,  277,   40,  277,  148,
      121,  121,  121,  277,  277,  277,   40,  277,  277,  277,
       86,  277,   40,   47,   47,   47,   38,  277,  277,  277,
      150,  151,   47,   47,  153,   38,   47,   47,   47,   38,
       86,  152,   47,   47,   47,   38,  277,   47,   47,   47,
       38,   47,   47,   47,   38,   47,   47,   47,   38,   47,
       47,   47,   38,  277,  277,  277,  154,  155,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,  277,  156,

      277,  277,  157,  277,  277,  160,   47,   47,   47,   38,
      277,  277,  158,  127,  159,   47,   47,   47,   38,   47,
       47,   47,   38,  277,  163,   47,   47,   47,   38,  277,
      277,  161,  277,  277,  162,   47,   47,   47,  139,  277,
      277,  165,   47,   47,   47,   38,  164,  277,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
      277,  277,  277,  166,  277,  167,  277,   37,   37,   37,
       38,   37,   37,   37,   38,   37,   37,   37,   38,  277,
      277,   37,   37,   37,   38,  171,  127,  168,  169,  277,
      277,  127,   40,  170,  172,  277,   40,  277,  277,  277,

       40,  118,   37,   37,   37,   38,   40,   47,   47,   47,
       38,   85,   47,  174,   47,   47,   47,   47,   38,  277,
      127,  277,   86,   47,   47,   47,   38,   40,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
      277,  175,   86,  277,  277,  277,  173,   47,   47,   47,
       38,  277,  277,  277,  177,  277,  277,  176,   47,   47,
       47,   38,  127,   47,   47,   47,   38,   47,   47,   47,
       38,   47,   47,   47,   38,  178,  277,  179,   47,   47,
       47,   38,   47,   47,   47,   38,  277,  277,  277,  181,
       47,   47,   47,   38,   47,   47,   47,   38,  277,  277,

      277,  182,  180,  183,   47,   47,   47,   38,   47,   47,
       47,   38,   37,   37,   37,   38,  277,  277,  277,  185,
      277,  184,  277,  277,  186,   37,   37,   37,   38,   37,
       37,   37,   38,  187,  277,  277,  127,   40,  277,  277,
      118,   37,   37,   37,   38,  277,  277,  188,  277,  118,
       40,  277,  277,  277,   40,  277,   85,   47,   47,   47,
      277,  277,  277,  189,  277,  191,   40,   86,  277,  277,
      277,  190,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,  277,  277,  277,   86,  277,   47,
       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,

       38,   47,   47,   47,   38,   47,   47,   47,   38,  277,
      277,  127,  277,  277,  192,  193,  277,  127,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
      277,  277,  277,  195,  277,  127,  277,  277,  277,  194,
       47,   47,   47,   38,  197,   47,   47,   47,   38,  277,
      277,  196,   47,   47,   47,   38,  198,  277,  277,  277,
      199,  277,   37,   37,   37,   38,   37,   37,   37,   38,
      277,  201,   47,   47,   47,   38,   47,   47,   47,   38,
      277,  277,  202,  277,  277,  277,  200,   40,  277,  277,
      277,   40,   47,   47,   47,   38,  277,   47,   47,   47,

       38,  277,  206,  277,  277,  277,  203,  277,  204,   47,
       47,   47,   38,   47,   47,   47,   38,  277,  207,   47,
       47,   47,   38,  277,  277,  277,  208,  127,   47,   47,
       47,   38,   47,   47,   47,   38,  277,  277,  277,  209,
       47,   47,   47,   38,   47,   47,   47,   38,  277,   37,
       37,   37,   38,   47,   47,   47,   38,  210,   37,   37,
       37,   38,  213,  211,   47,   47,   47,   38,   47,   47,
       47,   38,  218,  214,   40,  277,  277,  127,  212,  215,
      277,  277,  277,   40,  216,   47,   47,   47,   38,   47,
       47,   47,   38,  277,  277,  277,  220,   47,   47,   47,

       38,  277,   47,   47,   47,   38,  277,  219,   47,   47,
       47,   38,  277,  127,   47,   47,   47,   38,  277,  224,
      277,  277,  225,  221,  277,  226,  277,  227,  277,  277,
      277,  222,  223,  228,   37,   37,   37,   38,   37,   37,
       37,   38,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,  277,   40,
      277,  277,  277,   40,   47,   47,   47,   38,   47,   47,
       47,   38,  277,  277,  277,  118,  229,  277,  127,   47,
       47,   47,   38,  277,  277,  277,  231,  277,  277,  232,
       47,   47,   47,   38,  277,  277,  277,  235,  277,  277,

      233,   47,   47,   47,   38,   47,   47,   47,   38,  277,
      234,   47,   47,   47,   38,  277,  277,  277,  236,  277,
      277,   37,   37,   37,   38,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,  277,  277,  237,
      238,  277,  277,  277,  240,  239,   40,  241,  277,  277,
      277,  243,   47,   47,   47,   38,   47,   47,   47,   38,
      277,  277,  277,  245,   47,   47,   47,   38,   47,   47,
       47,   38,  277,  244,  277,  247,   47,   47,   47,   38,
      277,  277,  246,   47,   47,   47,   38,   47,   47,   47,
       38,   37,   37,   37,   38,   47,   47,   47,   38,   47,

       47,   47,   38,   47,   47,   47,   38,  277,  248,  277,
      277,  277,  249,  277,  255,  277,   40,  277,  277,  277,
      127,  277,  250,   47,   47,   47,   38,  251,  118,  254,
      277,  277,  277,  253,  256,   47,   47,   47,   38,   47,
       47,   47,   38,   47,   47,   47,   38,  277,   47,   47,
       47,   38,   47,   47,   47,   38,   47,   47,   47,   38,
       47,   47,   47,   38,   47,   47,   47,   38,  277,  258,
      277,  277,  277,  127,   47,   47,   47,   38,  277,  257,
      127,   47,   47,   47,   38,   47,   47,   47,   38,  277,
      277,  277,  260,  277,  259,  277,  277,  127,   47,   47,

       47,   38,  277,  261,   47,   47,   47,   38,   47,   47,
       47,   38,  277,  262,  277,  277,  277,  264,   47,   47,
       47,   38,  277,  263,   47,   47,   47,   38,  277,   47,
       47,   47,   38,  277,  265,   47,   47,   47,   38,  277,
      277,  277,  127,   47,   47,   47,   38,  277,   47,   47,
       47,   38,  266,   47,   47,   47,   38,  277,  268,  269,
      277,  277,  267,   47,   47,   47,   38,   47,   47,   47,
       38,  277,  277,  270,  277,  277,  277,  127,  271,   47,
       47,   47,   38,   47,   47,   47,   38,   47,   47,   47,
       38,  277,  272,   47,   47,   47,   38,  277,  277,  273,

       47,   47,   47,   38,  277,  127,   47,   47,   47,   38,
      277,  274,  277,  277,  277,  127,  277,  275,  277,  277,
      277,  277,  277,  276,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  127,  277,  277,  277,  277,  277,  127,   39,
       39,   39,   48,   48,    3,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277
    } ;

static const flex_int16_t yy_chk[1817] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    8,    8,    8,   11,   11,   11,   11,   33,
       33,   33,    8,   12,   12,   12,   12,   13,   13,   13,
       13,   14,   14,   14,   14,  280,   13,   74,   74,   74,
       11,   13,    8,  242,   15,   15,   15,   15,   12,   75,

       75,   75,   13,   13,  230,  217,   14,   12,   15,   16,
       16,   16,   16,   17,   17,   17,   17,  205,   14,   15,
       18,   18,   18,   18,   19,   19,   19,   19,   20,   20,
       20,   20,  191,   21,   21,   21,   21,   78,   32,   17,
       22,   22,   22,   22,   23,   23,   23,   23,   16,   10,
       19,    9,    5,   17,   19,   24,   24,   24,   24,   76,
       76,   76,   17,   21,   19,   20,   25,   25,   25,   25,
       23,   26,   26,   26,   26,   27,   27,   27,   27,   22,
       29,   29,   29,   29,   23,   24,   28,   28,   28,   28,
       30,   30,   30,   30,    3,   24,   31,   31,   31,   31,

        0,   27,    0,    0,   27,   27,   34,   34,   34,   34,
        0,   26,    0,   25,   85,   85,   85,   34,   35,   28,
       29,   35,   35,   35,   37,   37,   37,   37,    0,   30,
       28,   39,   39,   39,   39,   37,    0,   34,    0,   31,
       41,   41,   41,   41,   42,   42,   42,   42,   43,   43,
       43,   43,  113,  113,  113,   37,   39,    0,    0,   42,
       44,   44,   44,   44,    0,   41,    0,   77,   43,   42,
       77,   77,   77,   43,   45,   45,   45,   45,   46,   46,
       46,   46,    0,    0,   41,   44,   47,   47,   47,   47,
        0,   46,   48,   48,   48,   48,    0,   47,   44,   45,

       45,    0,    0,   46,   49,   49,   49,   49,   50,   50,
       50,   50,   51,   51,   51,   51,    0,   47,   52,   52,
       52,   52,   53,   53,   53,   53,   54,   54,   54,   54,
       55,   55,   55,   55,   56,   56,   56,   56,   57,   57,
       57,   57,    0,   58,   58,   58,   58,   61,   61,   61,
       61,   50,   51,   49,   54,   59,   59,   59,   59,  114,
      114,  114,   52,   73,   73,   73,   53,   60,   60,   60,
       60,    0,    0,   73,   56,   55,  122,  122,  122,   61,
       62,   62,   62,   62,    0,    0,   57,   58,   63,   63,
       63,   63,    0,   73,   59,   64,   64,   64,   64,   65,

       65,   65,   65,  123,  123,  123,   60,    0,   66,   66,
       66,   66,    0,    0,   67,   67,   67,   67,    0,   62,
        0,    0,   62,    0,    0,   63,   68,   68,   68,   68,
       69,   69,   69,   69,   70,   70,   70,   70,   64,   66,
       67,    0,    0,   65,   71,   71,   71,   71,   72,   72,
       72,   72,    0,   79,   79,   79,   79,    0,    0,   80,
       80,   80,   80,    0,   86,    0,   68,   86,   86,   86,
       70,    0,   69,   81,   81,   81,   81,   72,   79,   82,
       82,   82,   82,   79,   80,   80,    0,   71,    0,   81,
       83,   83,   83,   83,   84,   84,   84,   84,   81,   87,

       87,   87,   87,    0,   82,    0,    0,   84,    0,   82,
       88,   88,   88,   88,    0,   83,    0,    0,    0,   84,
       87,    0,    0,    0,   83,   89,   89,   89,   89,   90,
       90,   90,   90,   91,   91,   91,   91,    0,    0,    0,
       88,   92,   92,   92,   92,   93,   93,   93,   93,    0,
       94,   94,   94,   94,   96,   96,   96,   96,    0,   90,
        0,    0,   89,   91,    0,   95,   95,   95,   95,    0,
        0,    0,   93,   95,    0,   92,   94,   97,   97,   97,
       97,    0,    0,    0,   96,   98,   98,   98,   98,   99,
       99,   99,   99,  100,  100,  100,  100,  101,  101,  101,

      101,  102,  102,  102,  102,    0,    0,    0,  100,   97,
      100,  103,  103,  103,  103,   99,    0,   98,  104,  104,
      104,  104,  105,  105,  105,  105,  106,  106,  106,  106,
      107,  107,  107,  107,    0,  101,  108,  108,  108,  108,
        0,  109,  109,  109,  109,  103,  110,  110,  110,  110,
        0,    0,  104,  111,  111,  111,  111,  112,  112,  112,
        0,    0,    0,  106,    0,  105,    0,  112,    0,    0,
      108,  109,  107,  115,  115,  115,  115,    0,    0,    0,
      110,  116,  116,  116,  116,    0,    0,  112,  117,  117,
      117,  117,  118,  118,  118,  118,    0,    0,  115,    0,

      117,  119,  119,  119,  119,    0,  116,  120,  120,  120,
      120,    0,    0,  117,    0,  115,    0,  118,    0,  116,
      121,  121,  121,    0,    0,    0,  119,    0,    0,    0,
      121,    0,  120,  124,  124,  124,  124,    0,    0,    0,
      119,  120,  125,  125,  125,  125,  126,  126,  126,  126,
      121,  124,  127,  127,  127,  127,    0,  128,  128,  128,
      128,  129,  129,  129,  129,  130,  130,  130,  130,  131,
      131,  131,  131,    0,    0,    0,  126,  128,  132,  132,
      132,  132,  133,  133,  133,  133,  134,  134,  134,  134,
      135,  135,  135,  135,  136,  136,  136,  136,    0,  129,

        0,    0,  130,    0,    0,  134,  137,  137,  137,  137,
        0,    0,  132,  131,  133,  138,  138,  138,  138,  140,
      140,  140,  140,    0,  136,  141,  141,  141,  141,    0,
        0,  134,    0,    0,  135,  142,  142,  142,  142,    0,
        0,  138,  143,  143,  143,  143,  137,    0,  144,  144,
      144,  144,  145,  145,  145,  145,  146,  146,  146,  146,
        0,    0,    0,  140,    0,  141,    0,  147,  147,  147,
      147,  148,  148,  148,  148,  149,  149,  149,  149,    0,
        0,  150,  150,  150,  150,  149,  143,  144,  146,    0,
        0,  145,  147,  147,  150,    0,  148,    0,    0,    0,

      149,  148,  151,  151,  151,  151,  150,  152,  152,  152,
      152,  153,  153,  153,  153,  154,  154,  154,  154,    0,
      152,    0,  153,  155,  155,  155,  155,  151,  156,  156,
      156,  156,  157,  157,  157,  157,  158,  158,  158,  158,
        0,  154,  153,    0,    0,    0,  151,  159,  159,  159,
      159,    0,    0,    0,  156,    0,    0,  155,  160,  160,
      160,  160,  157,  161,  161,  161,  161,  162,  162,  162,
      162,  163,  163,  163,  163,  158,    0,  159,  164,  164,
      164,  164,  165,  165,  165,  165,    0,    0,    0,  161,
      166,  166,  166,  166,  167,  167,  167,  167,    0,    0,

        0,  162,  160,  163,  168,  168,  168,  168,  169,  169,
      169,  169,  170,  170,  170,  170,    0,    0,    0,  165,
        0,  164,    0,    0,  166,  171,  171,  171,  171,  172,
      172,  172,  172,  167,    0,    0,  168,  170,    0,    0,
      171,  173,  173,  173,  173,    0,    0,  169,    0,  170,
      171,    0,    0,    0,  172,    0,  174,  174,  174,  174,
        0,    0,    0,  172,    0,  174,  173,  174,    0,    0,
        0,  173,  175,  175,  175,  175,  176,  176,  176,  176,
      177,  177,  177,  177,    0,    0,    0,  174,    0,  178,
      178,  178,  178,  179,  179,  179,  179,  180,  180,  180,

      180,  181,  181,  181,  181,  182,  182,  182,  182,    0,
        0,  175,    0,    0,  176,  178,    0,  177,  183,  183,
      183,  183,  184,  184,  184,  184,  185,  185,  185,  185,
        0,    0,    0,  181,    0,  179,    0,    0,    0,  180,
      186,  186,  186,  186,  183,  187,  187,  187,  187,    0,
        0,  182,  188,  188,  188,  188,  184,    0,    0,    0,
      185,    0,  189,  189,  189,  189,  190,  190,  190,  190,
        0,  187,  192,  192,  192,  192,  193,  193,  193,  193,
        0,    0,  188,    0,    0,    0,  186,  189,    0,    0,
        0,  190,  194,  194,  194,  194,    0,  195,  195,  195,

      195,    0,  192,    0,    0,    0,  189,    0,  190,  196,
      196,  196,  196,  197,  197,  197,  197,    0,  193,  198,
      198,  198,  198,    0,    0,    0,  194,  195,  199,  199,
      199,  199,  200,  200,  200,  200,    0,    0,    0,  196,
      201,  201,  201,  201,  202,  202,  202,  202,    0,  203,
      203,  203,  203,  206,  206,  206,  206,  197,  204,  204,
      204,  204,  200,  198,  207,  207,  207,  207,  208,  208,
      208,  208,  206,  202,  203,    0,    0,  201,  199,  203,
        0,    0,    0,  204,  204,  209,  209,  209,  209,  210,
      210,  210,  210,    0,    0,    0,  209,  211,  211,  211,

      211,    0,  212,  212,  212,  212,    0,  208,  213,  213,
      213,  213,    0,  207,  214,  214,  214,  214,    0,  213,
        0,    0,  214,  210,    0,  214,    0,  214,    0,    0,
        0,  211,  212,  214,  215,  215,  215,  215,  216,  216,
      216,  216,  218,  218,  218,  218,  219,  219,  219,  219,
      220,  220,  220,  220,  221,  221,  221,  221,    0,  215,
        0,    0,    0,  216,  222,  222,  222,  222,  223,  223,
      223,  223,    0,    0,    0,  216,  215,    0,  219,  224,
      224,  224,  224,    0,    0,    0,  218,    0,    0,  220,
      225,  225,  225,  225,    0,    0,    0,  223,    0,    0,

      221,  226,  226,  226,  226,  227,  227,  227,  227,    0,
      222,  228,  228,  228,  228,    0,    0,    0,  224,    0,
        0,  229,  229,  229,  229,  231,  231,  231,  231,  232,
      232,  232,  232,  233,  233,  233,  233,    0,    0,  225,
      226,    0,    0,    0,  228,  227,  229,  229,    0,    0,
        0,  231,  234,  234,  234,  234,  235,  235,  235,  235,
        0,    0,    0,  233,  236,  236,  236,  236,  237,  237,
      237,  237,    0,  232,    0,  235,  238,  238,  238,  238,
        0,    0,  234,  239,  239,  239,  239,  240,  240,  240,
      240,  241,  241,  241,  241,  243,  243,  243,  243,  244,

      244,  244,  244,  245,  245,  245,  245,    0,  236,    0,
        0,    0,  237,    0,  245,    0,  241,    0,    0,    0,
      238,    0,  239,  246,  246,  246,  246,  240,  241,  244,
        0,    0,    0,  243,  246,  247,  247,  247,  247,  248,
      248,  248,  248,  249,  249,  249,  249,    0,  250,  250,
      250,  250,  251,  251,  251,  251,  253,  253,  253,  253,
      254,  254,  254,  254,  255,  255,  255,  255,    0,  248,
        0,    0,    0,  249,  256,  256,  256,  256,    0,  247,
      250,  257,  257,  257,  257,  258,  258,  258,  258,    0,
        0,    0,  254,    0,  251,    0,    0,  253,  259,  259,

      259,  259,    0,  255,  260,  260,  260,  260,  261,  261,
      261,  261,    0,  256,    0,    0,    0,  258,  262,  262,
      262,  262,    0,  257,  263,  263,  263,  263,    0,  264,
      264,  264,  264,    0,  260,  265,  265,  265,  265,    0,
        0,    0,  259,  266,  266,  266,  266,    0,  267,  267,
      267,  267,  261,  268,  268,  268,  268,    0,  263,  264,
        0,    0,  262,  269,  269,  269,  269,  270,  270,  270,
      270,    0,    0,  266,    0,    0,    0,  265,  267,  271,
      271,  271,  271,  272,  272,  272,  272,  273,  273,  273,
      273,    0,  268,  274,  274,  274,  274,    0,    0,  270,

      275,  275,  275,  275,    0,  269,  276,  276,  276,  276,
        0,  271,    0,    0,    0,  272,    0,  273,    0,    0,
        0,    0,    0,  274,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  275,    0,    0,    0,    0,    0,  276,  278,
      278,  278,  279,  279,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[14] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexico.l"
#line 2 "Lexico.l"
// Inclusões de bibliotecas
#include <iostream>
#include <string>
#include <unordered_map>
#include <algorithm>
#include <vector>
#include <cstring>
#include "symtable.h"
using std::cout;
using std::string;
using std::unordered_map;
using std::transform;
using std::vector;

#include "Sintatico.tab.h" 

// Definição da tabela de palavras reservadas
unordered_map<string, int> reservadas = {
    {"only", ONLY},
    {"some", SOME},
    {"all", ALL},
    {"value", VALUE},
    {"min", MIN},
    {"max", MAX},
    {"exactly", EXACTLY},
    {"that", THAT},
    {"not", NOT},
    {"and", AND},
    {"or", OR},
    {"class:", CLASS},
    {"equivalentto:", EQUIVALENTTO},
    {"individuals:", INDIVIDUALS},
    {"subclassof:", SUBCLASSOF},
    {"disjointclasses:", DISJOINTCLASSES},
    {"disjointwith:", DISJOINTWITH}
};

// Definição de funções auxiliares
string toLower(string str);

// Definição de variáveis globais
bool erro = false;
int line_number = 1;
extern SymTable * currentTable;
#line 1004 "lex.yy.c"
#define YY_NO_INPUT 1
#line 1006 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 69 "Lexico.l"

#line 1223 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 278 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1755 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 70 "Lexico.l"
{ line_number++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 71 "Lexico.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "Lexico.l"
{
    switch (yytext[0]) {
        case '<':
            if (yytext[1] == '=') {
                return TAG_MENORIGUAL;  // '<='
            } else {
                return TAG_MENOR;       // '<'
            }
        case '>':
            if (yytext[1] == '=') {
                return TAG_MAIORIGUAL;  // '>='
            } else {
                return TAG_MAIOR;       // '>'
            }
        case '[':
            return TAG_ABRECOLCHETE;  // '['
        case ']':
            return TAG_FECHACOLCHETE;  // ']'
        case '{':
            return TAG_ABRECHAVE;     // '{'
        case '}':
            return TAG_FECHACHAVE;    // '}'
        case '(':
            return TAG_ABREPARANTESIS;  // '('
        case ')':
            return TAG_FECHAPARANTESIS;  // ')'
        case ',':
            return TAG_VIRGULA;        // ','
        case ':':
            return TAG_DOISPONTOS;     // ':'
        default:
            return 0;  // caso de erro
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "Lexico.l"
{ yylval.str = strdup(yytext); return TAG_NAMESPACE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "Lexico.l"
{ yylval.str = strdup(yytext); return TAG_DATATYPE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 108 "Lexico.l"
{ yylval.num = atof(yytext); return TAG_NUM; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "Lexico.l"
{ 
    std::string className = yytext;
    Symblo newSymblo = {currentTable->getClassName()};  
    currentTable->Insert(className, newSymblo);  
    yylval.str = strdup(yytext); 
    return TAG_INDIVIDUOS; 
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 116 "Lexico.l"
{
    auto it = reservadas.find(toLower(yytext)); 
    if (it != reservadas.end()) {
        return it->second;
    } else {
        if (currentTable->getClassName().empty())
        {
            std::string className = yytext;
            currentTable->setClassName(className);
        }
        yylval.str = strdup(yytext);
        return TAG_CLASS;
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 130 "Lexico.l"
{ cout << "Erro lexico encontrado na linha " << line_number << ": " << yytext << "\n"; erro = true; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "Lexico.l"
{
    auto it = reservadas.find(toLower(yytext));
    if (it != reservadas.end()) {
        return it->second;
    } else {
        yylval.str = strdup(yytext);
        return TAG_PROPERTY;
    }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 140 "Lexico.l"
{
    auto it = reservadas.find(toLower(yytext)); 
    if (it != reservadas.end()) {
        if (it->second == CLASS) {
            // Nova tabela de símbolos
            SymTable * newScope = new SymTable(currentTable);
            currentTable = newScope;
        }
        return it->second; 
    } else {
        cout << "Erro lexico encontrado na linha " << line_number << ": " << yytext << "\n";
        erro = true;
    }
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "Lexico.l"
{ cout << "\nErro lexico encontrado na linha " << line_number << ": " << yytext << "\n"; erro = true; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 155 "Lexico.l"
ECHO;
	YY_BREAK
#line 1429 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 278 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 278 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 277);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 155 "Lexico.l"


string toLower(string str) {
    transform(str.begin(), str.end(), str.begin(), [](unsigned char c) { return tolower(c); });
    return str;
}
